import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "../../..");
const componentPath = path.join(rootDir, "src", "components", "ui", "video-hero-section.tsx");
const pagePath = path.join(rootDir, "src", "app", "page.tsx");
const i18nPath = path.join(rootDir, "src", "lib", "i18n.tsx");

test("home hero uses the pointer image typography layout instead of cards or video", () => {
  assert.ok(existsSync(componentPath), "expected video hero component to exist");

  const source = readFileSync(componentPath, "utf8");

  assert.match(source, /useI18n/);
  assert.match(source, /\/hero_image\/pointerhigh1\.png/);
  assert.doesNotMatch(source, /\/hero_image\/pointerhigh\.png/);
  assert.doesNotMatch(source, /\/hero_image\/pointer\.png/);
  assert.match(source, /t\.videoHero\.columns/);
  assert.match(source, /t\.videoHero\.alwaysFree/);
  assert.match(source, /heroColumnStyles/);
  assert.doesNotMatch(source, /title: "one"/);
  assert.doesNotMatch(source, /word: "Resume"/);
  assert.doesNotMatch(source, /word: "Interview"/);
  assert.doesNotMatch(source, /title: "GET"/);
  assert.doesNotMatch(source, /word: "Matched"/);
  assert.doesNotMatch(source, /It's environmentally friendly/);
  assert.doesNotMatch(source, /It's environment friendly/);
  assert.doesNotMatch(source, /Enough for skilled/);
  assert.doesNotMatch(source, /Sophie Chen/);
  assert.doesNotMatch(source, /Norva|Avenir|Pilot/);
  assert.doesNotMatch(source, /92% match/);
  assert.doesNotMatch(source, /Loved by 10,000\+ candidates/);
  assert.doesNotMatch(source, /lucide-react/);
  assert.match(source, /import Link from "next\/link"/);
  assert.doesNotMatch(source, /\/hero_video\/handshake\.mp4/);
  assert.doesNotMatch(source, /<video/);
  assert.match(source, /var\(--font-geist-sans\)/);
});

test("home page renders video hero before the existing laptop hero", () => {
  const source = readFileSync(pagePath, "utf8");

  assert.match(source, /VideoHeroSection/);
  assert.match(source, /<VideoHeroSection \/>\s*<HeroIsolationTestSection mode="home" \/>/);
});

test("home hero CTA labels match the screenshot button treatment", () => {
  const translations = readFileSync(i18nPath, "utf8");

  assert.match(translations, /columns: \[/);
  assert.match(translations, /title: "one"/);
  assert.match(translations, /word: "Resume"/);
  assert.match(translations, /note: "It's environmentally friendly"/);
  assert.match(translations, /word: "Interview"/);
  assert.match(translations, /note: "Enough for skilled"/);
  assert.match(translations, /title: "GET"/);
  assert.match(translations, /word: "Matched"/);
  assert.match(translations, /alwaysFree: "Always free"/);
  assert.match(translations, /Upload your CV once, then stop repeating yourself\./);
  assert.match(translations, /One profile, matched to companies that fit\./);
  assert.match(translations, /primaryCta: "Start the interview"/);
  assert.match(translations, /secondaryCta: "For companies"/);
  assert.match(translations, /alwaysFree: "Sempre gratis"/);
  assert.match(translations, /alwaysFree: "Toujours gratuit"/);
});

test("home hero keeps the same centered composition across breakpoints", () => {
  const source = readFileSync(componentPath, "utf8");

  assert.match(source, /grid-cols-3/);
  assert.match(source, /min-h-\[100svh\]/);
  assert.match(source, /justify-start/);
  assert.match(source, /sm:justify-center/);
  assert.match(source, /pt-\[9rem\]/);
  assert.doesNotMatch(source, /pt-\[11\.5rem\]/);
  assert.match(source, /sm:pt-\[clamp\(5\.4rem,12vh,7\.25rem\)\]/);
  assert.match(source, /z-\[1\]/);
  assert.match(source, /overflow-x-clip/);
  assert.match(source, /overflow-y-visible/);
  assert.doesNotMatch(source, /overflow-hidden/);
  assert.doesNotMatch(source, /min-h-\[clamp\(560px,72svh,680px\)\]/);
  assert.match(source, /max-w-\[720px\]/);
  assert.match(source, /relative z-10 block h-\[34\.25rem\] w-full max-w-\[390px\] sm:hidden/);
  assert.doesNotMatch(source, /relative z-10 block h-\[28rem\] w-full max-w-\[390px\] sm:hidden/);
  assert.doesNotMatch(source, /relative z-10 block h-\[31rem\] w-full max-w-\[390px\] sm:hidden/);
  assert.doesNotMatch(source, /relative z-10 block h-\[32\.25rem\] w-full max-w-\[390px\] sm:hidden/);
  assert.doesNotMatch(source, /relative z-10 block h-\[38\.5rem\] w-full max-w-\[390px\] sm:hidden/);
  assert.match(source, /left-\[2\.1rem\] top-0/);
  assert.match(source, /right-\[1\.15rem\] top-\[5\.45rem\]/);
  assert.match(source, /right-\[0\.55rem\] top-\[18\.75rem\]/);
  assert.doesNotMatch(source, /right-\[1\.05rem\] top-\[5\.45rem\]/);
  assert.doesNotMatch(source, /right-\[0\.25rem\] top-\[18\.75rem\]/);
  assert.doesNotMatch(source, /right-\[4\.1rem\] top-\[5\.45rem\]/);
  assert.doesNotMatch(source, /right-\[2\.55rem\] top-\[18\.75rem\]/);
  assert.doesNotMatch(source, /right-\[3\.8rem\] top-\[18\.75rem\]/);
  assert.match(source, /mobileTitleClassName/);
  assert.match(source, /mobileWordClassName/);
  assert.match(source, /desktopClassName/);
  assert.match(source, /desktopTitleClassName/);
  assert.match(source, /hidden w-full max-w-\[720px\] grid-cols-3/);
  assert.match(source, /sm:grid/);
  assert.match(source, /text-\[clamp\(1\.9rem,6\.6vw,4\.8rem\)\]/);
  assert.match(source, /sm:-translate-x-\[clamp\(0\.75rem,2\.35vw,2\.85rem\)\]/);
  assert.match(source, /text-\[clamp\(1\.85rem,5\.85vw,4\.35rem\)\]/);
  assert.match(source, /text-\[clamp\(1\.28rem,3\.75vw,2\.82rem\)\]/);
  assert.match(source, /text-\[3\.55rem\]/);
  assert.match(source, /text-\[2\.2rem\]/);
  assert.match(source, /text-\[4\.05rem\]/);
  assert.match(source, /text-\[2\.5rem\]/);
  assert.doesNotMatch(source, /text-\[3\.9rem\]/);
  assert.doesNotMatch(source, /text-\[2\.42rem\]/);
  assert.match(source, /pointer-events-none absolute/);
  assert.match(source, /left-\[max\(-44vw,-180px\)\]/);
  assert.doesNotMatch(source, /left-\[max\(-40vw,-165px\)\]/);
  assert.doesNotMatch(source, /left-\[max\(-27vw,-108px\)\]/);
  assert.doesNotMatch(source, /left-\[max\(-30vw,-120px\)\]/);
  assert.doesNotMatch(source, /left-\[max\(-32vw,-130px\)\]/);
  assert.doesNotMatch(source, /left-\[max\(-45vw,-190px\)\]/);
  assert.match(source, /right-auto/);
  assert.match(source, /top-\[13\.6rem\]/);
  assert.match(source, /h-\[clamp\(420px,110vw,500px\)\]/);
  assert.match(source, /sizes="\(max-width: 639px\) 110vw, 820px"/);
  assert.match(source, /preload/);
  assert.match(source, /unoptimized/);
  assert.doesNotMatch(source, /loading="lazy"/);
  assert.doesNotMatch(source, /priority/);
  assert.doesNotMatch(source, /top-\[16\.1rem\]/);
  assert.doesNotMatch(source, /top-\[16\.4rem\]/);
  assert.doesNotMatch(source, /h-\[clamp\(350px,91vw,420px\)\]/);
  assert.doesNotMatch(source, /sizes="\(max-width: 639px\) 91vw, 820px"/);
  assert.doesNotMatch(source, /top-\[18\.2rem\]/);
  assert.doesNotMatch(source, /top-\[17rem\]/);
  assert.doesNotMatch(source, /h-\[clamp\(330px,86vw,390px\)\]/);
  assert.match(source, /sm:left-auto/);
  assert.match(source, /sm:right-\[max\(-24vw,-320px\)\]/);
  assert.match(source, /sm:top-\[clamp\(4\.2rem,9vh,5\.8rem\)\]/);
  assert.match(source, /sm:h-\[clamp\(360px,80vw,820px\)\]/);
  assert.match(source, /width=\{1254\}/);
  assert.match(source, /height=\{1254\}/);
  assert.match(source, /scale-x-100/);
  assert.match(source, /sm:-scale-x-100/);
  assert.doesNotMatch(source, /transform: "scaleX\(-1\)"/);
  assert.doesNotMatch(source, /right-0/);
  assert.doesNotMatch(source, /right-\[max\(-34vw,-390px\)\]/);
  assert.doesNotMatch(source, /right-\[max\(-42vw,-520px\)\]/);
  assert.doesNotMatch(source, /right-0 top-0/);
  assert.doesNotMatch(source, /h-\[clamp\(360px,80vw,820px\)\] w-auto max-w-none select-none object-contain"/);
  assert.doesNotMatch(source, /h-\[min\(72vw,640px\)\]/);
  assert.doesNotMatch(source, /h-\[clamp\(320px,72vw,680px\)\]/);
  assert.doesNotMatch(source, /top-\[15%\]/);
  assert.match(source, /t\.videoHero\.primaryCta/);
  assert.match(source, /t\.videoHero\.secondaryCta/);
  assert.match(source, /href="\/candidate"/);
  assert.match(source, /href="\/product\/companies"/);
  assert.match(source, /prefetch=\{false\}/);
  assert.doesNotMatch(source, /href="#begin"/);
  assert.doesNotMatch(source, /href="#companies"/);
  assert.match(source, /t\.videoHero\.alwaysFree/);
  assert.doesNotMatch(source, />\s*Always free\s*</);
  assert.match(source, /textPath/);
  assert.match(source, /always-free-arc/);
  assert.match(source, /-translate-x-\[58%\]/);
  assert.doesNotMatch(source, /-translate-x-\[78%\]/);
  assert.match(source, /bg-\[#1800ad\]/);
  assert.doesNotMatch(source, /bg-\[#2100c8\]/);
  assert.match(source, /bg-\[#d8d8d8\]/);
  assert.match(source, /h-\[3rem\]/);
  assert.match(source, /sm:h-\[clamp\(2\.45rem,4\.45vw,3\.35rem\)\]/);
  assert.match(source, /w-\[10\.55rem\]/);
  assert.match(source, /w-\[9\.85rem\]/);
  assert.match(source, /text-\[1\.14rem\]/);
  assert.match(source, /sm:text-\[clamp\(0\.95rem,2\.25vw,1\.8rem\)\]/);
  assert.match(source, /h-\[4\.3rem\]/);
  assert.match(source, /w-\[3\.55rem\]/);
  assert.match(source, /sm:h-\[clamp\(3\.7rem,6\.2vw,5\.2rem\)\]/);
  assert.match(source, /mt-0 flex items-center justify-center/);
  assert.match(source, /sm:mt-\[clamp\(5\.4rem,15vh,8\.3rem\)\]/);
  assert.match(source, /mt-4 max-w-\[380px\] text-center text-\[0\.55rem\]/);
  assert.match(source, /sm:mt-7 sm:max-w-\[780px\]/);
  assert.match(source, /sm:w-\[clamp\(8\.9rem,15\.4vw,11\.6rem\)\]/);
  assert.match(source, /sm:w-\[clamp\(8\.7rem,16\.5vw,12\.4rem\)\]/);
  assert.doesNotMatch(source, /w-\[clamp\(9\.5rem,17\.5vw,14\.75rem\)\]/);
  assert.doesNotMatch(source, /h-\[clamp\(3\.7rem,8\.1vw,5\.55rem\)\]/);
  assert.doesNotMatch(source, /w-\[clamp\(13rem,29vw,26\.2rem\)\]/);
  assert.doesNotMatch(source, /lg:grid-cols-\[0\.86fr_1\.14fr\]/);
  assert.doesNotMatch(source, /CompanyLogo|companyMatches|candidateSkills|candidateAvatars/);
});
